title: H₂Go!
email: olivier.patry@gmail.com
description: >-
  Your minimalist companion for daily water tracking.
  Built with a modern Android stack, H₂Go! is designed to be simple, fast, and supportive.
  Just one tap to log your water, right from the app or your home screen.
baseurl: '/h2go'
url: 'https://opatry.github.io'
