on:
  workflow_call:

jobs:
  coverage:
    name: 📊 Coverage
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-jdk-gradle

    # Avoid using --parallel for coverage reporting, seems unreliable when doing it
    - name: 📊 Check coverage
      if: github.event_name == 'pull_request'
      run: |
        ./gradlew --no-daemon --console=plain \
          koverLogCoverage koverVerifyCoverage
